@startuml
title Fatigue Calculation

Actor User
participant "App Service" as app
participant "Data Collectors" as sensors
participant "Data Controller" as data
participant "CoreData" as storage
participant "Fatigue Processor" as fatigue
participant "Notifications Manager" as notifications
participant "Interface Manager" as interface
User -> app : Watch turned on / App begins
app -> data :Begin background tasks
storage -> data: Load base values
data -> sensors: Periodically query sensor data
sensors -> data : Return sensor data
data -> fatigue: Send data
fatigue -> fatigue : calculate fatigue
fatigue -> data : send calculated data
data -> storage : update database
alt Fatigue threshold passed
    fatigue -> notifications : Create notification
    notifications -> interface : Show notification
end

interface -> User : View notification / details

@enduml