' https://github.com/plantuml-stdlib/C4-PlantUML?tab=readme-ov-file#getting-started
' Useful library for creating C4 diagrams

@startuml Context-diagram
!include  https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

title "Context Diagram"

Person(user, "User", )
System_Ext(healthkit, "Apple HealthKit", "Historical repository of health data")
System_Ext(coreMotion, "Core Motion", "Reports motion-based data")
System(coreLocation, "Core Location", "Provides location-related data")

System(system, "Fatigue Management System", "Calculates user fatigue")

Rel_D(user, system, "Passively generates data")
Rel_U(healthkit, system, "Updates stored information")
Rel_U(coreMotion, system, "Provides motion-related data")
Rel_U(coreLocation, system, "Use stored data to calculate base values")


@enduml