@startuml container-diagram
!include  https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

title "System Container Diagram"


Person(user, "User", "Using the system")

System_Boundary(systemCont, "Fatigue Management System") {
    Container(ui, "App Interface", "Provides interface to user") 
    Container(service, "App Service", "Manages data movement through system") 
}

Container_Ext(healthkit, "Apple HealthKit", "Historical repository of health data")

' Internal relations
Rel_U(ui, user, "Interacts with app / passively generates data")
Rel_U(service, ui, "Provides fatigue and user data")
Rel_U(healthkit, service, "Data input into system")
@enduml