@startuml
title Fatigue Calculation

Actor User
participant "App Service" as app
participant "Sensor Manager" as sensorManager
participant "Data Processor" as processor
participant "Persistant Storage" as storage
participant "Notifications Manager" as notifications
participant "Interface Manager" as interface
User -> app : Watch turned on / App begins
storage -> processor: Load base values
app -> sensorManager : Periodically read sensor data
sensorManager -> processor : Send data
processor -> processor : calculate fatigue
processor -> storage : log data
alt Fatigue threshold passed
    processor-> notifications : Create notification
    notifications -> interface : Show notification
end

interface -> User : View notification / details

@enduml