@startuml data-controller-component-diagram
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

title "Data Controller Component Diagram"


Container_Boundary(controller, "Data Controller") {
    Component(healthAdpt, "Health Adapter", "Communicates with HealthKit")
    Component(locationAdpt, "Location Adapter", "Communicates with Core Location")
    Component(weatherAdpt, "Weather Adapter", "Communicates with Weatherkit")
    Component(motionAdpt, "Motion Adapter", "Communicates with Core Motion")
    Component(dbGateway, "Database Manager", "Provides Interface for CoreData")
    Component(coordinator, "Data Coordinator", "Coordinates requests to adapters")
    Component(aggregator, "Data Aggregator", "Aggregates collected data for storage and processing")
}

Component_Ext(healthkit, "Apple Healthkit", "Provides historical health data")
Component_Ext(coreLocation, "Location Manager", "Provides Location data")
Component_Ext(weatherkit, "Weatherkit", "provides weather data")
Component_Ext(coreMotion, "Core Motion", "Provides motion data")
Component_Ext(coreData, "CoreData Persistent Storage", "persistant storage for system")
Component_Ext(fatigueProc, "Fatigue Processor", "Calculates Fatigue")
Component_Ext(ui, "User Interface", "Displays gathered data")


' External relations
Rel_U(healthAdpt, healthkit, "Communicate with health repository")
Rel_U(locationAdpt, coreLocation, "Gather location data")
Rel_U(weatherAdpt, weatherkit, "Gathers weather data") 

Rel_U(motionAdpt, coreMotion, "Gather motion data")
Rel_U(dbGateway, coreData, "Communicate with database")


' Internal relations
Rel(healthAdpt, coordinator, "health data")
Rel(locationAdpt, coordinator, "location data")
Rel_R(locationAdpt, weatherAdpt, "Requires current location to fetch data")
Rel(weatherAdpt, coordinator, "Weather data")
Rel(motionAdpt, coordinator, "motion data")
Rel(dbGateway, coordinator, "system storage")

Rel_D(coordinator, aggregator, "Passed collected data for aggregation")
Rel_L(aggregator, dbGateway, "Stores aggregated data for long term")

Rel(aggregator, fatigueProc, "Passes collected data")
Rel(aggregator, ui, "Passes collected data")




@enduml